[package]
name = "rasuti"
version = "0.2.7"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.5.4"
dotenv = "0.15.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3